server {
    listen 80;
    server_name ha.lan;

    resolver 127.0.0.11 valid=30s;

    location / {
        proxy_pass http://homeassistant:8123;
        include /etc/nginx/proxy_params;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
    }
}
