server {
    listen 80;
    server_name n8n.lan;

    resolver 127.0.0.11 valid=30s;

    location / {
        proxy_pass http://n8n:5678;
        include /etc/nginx/proxy_params;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
