server {
    listen 80;
    server_name router.lan;

    resolver 127.0.0.11 valid=30s;

    location / {
        set $target http://ai-router:7860;
        proxy_pass $target;
        include /etc/nginx/proxy_params;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
